version: '3.6'

volumes:
  platadmin_nginx_logs:
  platadmin_composer_cache:
  platadmin_public_volume:
  
services:
  platform-admin:
#    image: qbonaventure/discord-bot-website:latest
    image: discord-platform-administration
    tty: true
    restart: always
    env_file:
      - .env
    volumes:
      - platadmin_composer_cache:/app/vendor
      - platadmin_public_volume:/app/public
    deploy:
      labels :
        ftcbot.service: platadmin
      replicas: 4
      update_config:
        parallelism: 2
        delay: 20s
      restart_policy:
        condition: on-failure
    networks:
      ftcbot:
      
  platadmin-front-server:
    image: qbonaventure/discord-website-server:1
    ports:
      - "7625:80"
    links: 
      - platadmin
    volumes:
      - website_nginx_logs:/var/log/nginx
      - website_public_volume:/app/public
    deploy:
      labels:
        ftcbot.service: platadmin-front-server
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
    networks:
      ftcbot:

      
networks:
  ftcbot:
    external: true
  traefik:
    external: true
